// <auto-generated />
namespace MyShop.DataAcess.InSQL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class orderssecond : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(orderssecond));
        
        string IMigrationMetadata.Id
        {
            get { return "201912170234585_orders-second"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
