// <auto-generated />
namespace MyShop.DataAcess.InSQL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class Custom : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Custom));
        
        string IMigrationMetadata.Id
        {
            get { return "201912161407498_Custom"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
